france:
  name-country: France
  price: 0.5
  percentage: 0.99
  currency: euro

morocco:
  name-country: Morocco
  price-base: 5
  price-increased: 6
  currency: dirham

spring:
  profiles:
    active: france